### PR TITLE
Add Behind

### PR DESCRIPTION
**Pull request by bear8642**
Add Behind and rearrange dyadic operators.

### CODE REVIEW

**Comment by bear8642** [comment]
Pull request for #1

**Comment by bear8642** [comment]
hrefs left empty as documentation pages don't currently exist

**Comment by bear8642** [comment]
Realised know what the links _should_ be, so add them now

**Review by abrudz — APPROVED** [review]

**Comment by bear8642** [comment]
Closes #2 #1

**Comment by bear8642** [comment]
Closes #1

**Pull request merged**
